proxmox-pkg_secrets: null
sops:
  lastmodified: "2026-04-13T02:48:58Z"
  mac: ENC[AES256_GCM,data:DlvoJCjmUW30twJKfm8oftmF2njD7kjerRpNsBHkVZcNujvCx1YTBGJiw7oLJp1CQAv42xjpMXdEHAS3aDryACPVxAVHDvhS+nxJ6k8GboaoiLo+7TPoperSXi3pfRLa1zrcCp+sY3M4ycCjT46V4LlC46B3y8gowGp4Gkln8FA=,iv:K7MU0RLIK+UNxi8OgpBFmcTVHJjX1u1fMDR0RZpMEIQ=,tag:u/MzyvilR+hQdeuU+GctgQ==,type:str]
  pgp:
    - created_at: "2026-04-13T02:48:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv/QBl9OS70/rhgZ/RG3iidXrrk8RKrxL9KjdJY6k1MHxkD
        ROaOIKcq7sXuWdyp4dmhKLw+B0m+kZ7MXqdVqnCQSWb9kYcm3HBJKE7bT3AyC2pC
        WRqbRAnDhE3lY9y2Mwq6jy5nlaycdqsCkulGGx3pzowi8HWo+rJODLvqLvhNaD2t
        cx18DIVA8k8r1ojl5/NiB/3OqNhMdzKKI8E6wTarj8PMGUcL3gS05EqakBVV4yVe
        JiFOsHPFtBd6+SdIRDUPGS+3XaJrEN+ivb4/uOTyYgxzSwT7cheQavkwFhSITtp7
        r0ifVf5G2sZi2H3NkC7hDDAhi5cIZG2EQeskPGysI8rjWbemyULVbn/SWMfizNsl
        WhxEGbcCo8VF4JbuhqAhf9pOqbIL8CRvAxeHLxve3hoU8fH/JPxBQJvXa06FnsTv
        6gIRw0jAygwYRxQyaq40FwrIL1IcVrwld1V2L2ey6EtsKBCloRjmprUadLc3ZNrI
        4B5SkpJw92jl/fPXfXVK0l4B5WjxMtvt/iWdQW69BD0Afjm2hPSH3y3vK7cvCjRa
        HiMDHkT2eg/ww7KUGFvcWL6NluSrvGjDqPdcu0jPlOoO0BXR94mE382Xg6QQtPgr
        F975gS9C4ln3+/v4gjgS
        =kSuN
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T02:48:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ/+JybY7RKYmpYt9yZCEobA/eKZkTYlqbr0zs/eQSTTqcCT
        ruv1MBf9JxlEx1RY9jsdajF7v13Ti8RUTJdN2iY0RRDCVXcs+iI7NKQ8gmAaNlgp
        VMXcbAUJ7i+/tV/B3bNXAQQIZVMtEwfNHD+yUQtD37pghMM3SWsI70DbUf2HJAGN
        7rNtK5CLT1SadS4JxL3O9xuRex0j1A2AN3QIrR5ne6tZo2UGgXHA+InRALdMyIgL
        wRzKPzSWR2r1rZBptBHgU/E1vTvGJE44+RrQ1Tn6WZs/XO7/AptpHjeqAtGUFeaT
        IRNyN8qTQgWEiuSQ9y5AcNh5Ohh+8ui3ugss+tGv6yxtyKABkv6EIGq8M4teUwXb
        4MvCanw09h5gSxlb+xpsiUopmg1X3EbSVYnbBI0pJma6+hiysKSrUYwvZ5slQJwy
        +ZUDmKArYUASnTiw0U2Fu/KcpDF6sm/3zjgIgOBXfhVtkOi0AL9v3oIR4ASU6NXx
        iPfPqezfMknjpNKAQvbFolrwhwmAK+fzVeQ+w8NehEfHhM8pu5DoKrQrFIe4NjoA
        /rEHGWyvrhJvzAWErKQhdZ3YvT8KnXCsqR68T+uePcMBVMJU2R84kIg94ryreUNl
        rR6RtErpMgVlIh8rGAI9kAhS3rgtCE2I6aNGiYKjf1MlCyIQUR8OdAKPWlFVU/XS
        XgFypXE6IOB73mdByiCrTCVwgjg7ZOv5hmTHpUsdXkJvApJx78BoQi8FA+7YOub0
        ahrKqbYlRhy6v5Ogo89YnBOgk3TGfFGQdpHdGkCtAPiM35g8+2oPntmVd0VfrWE=
        =cRr9
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
